databases:
  - name: nexdrive-db
    databaseName: neondb
    user: neondb_owner
    plan: free

services:
  - type: web
    name: nexdrive
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: nexdrive-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: nexdrive-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: nexdrive-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: nexdrive-db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: nexdrive-db
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION
        value: "86400000"
      - key: ALLOWED_ORIGINS
        value: "https://nexdrive-uwz7.onrender.com"
