package br.com.unipaulistana.rentacar.backend.domain;

public enum NotificationType {
    RESERVA_CONFIRMADA,
    RESERVA_CANCELADA,
    PAGAMENTO_APROVADO,
    PAGAMENTO_RECUSADO,
    LEMBRETE_RETIRADA,
    LEMBRETE_DEVOLUCAO,
    PRECO_REDUZIDO,
    VEICULO_DISPONIVEL,
    ABANDONO_RESERVA,
    AVALIACAO_POS_ALUGUEL,
    REENGAJAMENTO,
    ANIVERSARIO_CONTA,
    NOVO_LOGIN_DISPOSITIVO,
    ALTERACAO_SENHA,
    BOAS_VINDAS,
    PROMO_CADASTRO,
    SISTEMA
}
